schema: kata.ai/schema/merapi/1.0
name: "${package.name}"
version: "${package.version}"
plugins:
  - service
  - proxy
  - express
main: main
components:
  main: Main
  knex:
    type: component
    path: stores/knex
    load: true
  app:
    type: express
    config: app
  sampleManager: managers/sampleManager
  sampleController: controllers/sampleController
merapi:
  logging:
    level: info
stores:
  knex:
    client: "${$MYSQL_CLIENT}"
    connection:
      host: "${$MYSQL_HOST}"
      user: "${$MYSQL_USERNAME}"
      password: "${$MYSQL_PASSWORD}"
      port: "${$MYSQL_PORT}"
      database: "${$MYSQL_DATABASE}"
      db: "${$MYSQL_DATABASE}"
      encrypt: true
    pool:
      min: 2
      max: 10
    migrations:
      tableName: migrations
service:
  host: 0.0.0.0
  port: "${$SERVICE_PORT}"
  api.v1:
    hello: sampleManager.hello
app:
  host: 0.0.0.0
  port: "${$APP_PORT}"
  routes:
    GET /hello/:name?:
      - sampleController.hello