configs:

  redis:
    runInLocal: '{{ .GetValue "runRedisInLocal" }}'
    ports: |
      6379

  redisContainer:
    useImagePrefix: true
    imageName: ztpl-image-prefix-redis
    containerName: ztplContainerPrefixRedis
    localhost: host.docker.internal
    checkCommand: |
      echo "check redis"
    afterCheck:
      sleep 2
    volumes: |
