configs:

  elasticsearch:
    runInLocal: '{{ .GetValue "runElasticsearchInLocal" }}'
    ports: |
      9200
      9300

  elasticsearchContainer:
    useImagePrefix: true
    imageName: ztpl-image-prefix-elasticsearch
    containerName: ztplContainerPrefixElasticsearch
    localhost: host.docker.internal
    checkCommand: |
      echo "check elasticsearch"
    afterCheck:
      sleep 2
    volumes: |
