configs:

  makeZtplAppNameHelmDeploymentTask:
    _skipCreationPath: 'zaruba-tasks/${_ZRB_DEPLOYMENT_NAME}'
    _validateAppDirectory: ''
    _taskIndexPath: './zaruba-tasks/${_ZRB_DEPLOYMENT_NAME}/index.yaml'
    _registerAppRunnerTasks: ''
    templateLocations: |
      [
        "{{ .GetTaskPath "./deploymentTaskTemplate" }}"
      ]