configs:

  mysql:
    runInLocal: '{{ .GetValue "runMysqlInLocal" }}'
    ports: |
      3306

  mysqlContainer:
    useImagePrefix: true
    imageName: mysql
    containerName: ztplContainerPrefixMysql
    localhost: host.docker.internal
    checkCommand: |
      mysql -u "root" -p{{ .GetEnv "MYSQL_ROOT_PASSWORD" }} -e "SHOW SCHEMAS"
    volumes: |
      init.sql:/docker-entrypoint-initdb.d/init.sql