configs:

  mongodb:
    runInLocal: '{{ .GetValue "runMongodbInLocal" }}'
    ports: |
      27017

  mongodbContainer:
    useImagePrefix: true
    imageName: ztpl-image-prefix-mongodb
    containerName: ztplContainerPrefixMongodb
    localhost: host.docker.internal
    checkCommand: |
      echo "check mongodb"
    afterCheck:
      sleep 2
    volumes: |
